name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
     LOGIN: ${{ secrets.DOCKER_LOGIN }}
     NAME: ${{ secrets.DOCKER_NAME }}

    steps:
    - uses: actions/checkout@master
    
    - name: Login to docker.io
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      
    - name: Build the Docker image
      run: docker build -t $LOGIN/$NAME:latest --file Dockerfile .

    - name: Push image to docker.io
      run: docker push $LOGIN/$NAME:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: pulling
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          cd /usr/docker/${{ github.event.repository.name }}
          git pull
          docker compose pull
          docker compose up -d
